org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Dependencies
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.1]
forge_version=47.4.10
loader_version_range=[47,)
jei_version=15.20.0.106
# Mod Information
mod_id=bedrock_creative_tabs
mod_name=Bedrock Creative Tabs
mod_license=LGPL-3.0
mod_version=1.0
mod_group_id=com.iafenvoy.bct
